'use client';
import {useState,useEffect,useMemo,useCallback} from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,Legend} from 'recharts';
import {RefreshCw,Download,Users,CalendarDays,Layers,LogOut,Search,MapPin,Clock,Phone,LockKeyhole,Copy,Printer,Footprints,Ship,Bird,Flower2,Plane,ExternalLink,ChevronRight,Eye,Check} from 'lucide-react';
import {ACTIVITY_INFO,type LiveData,type Participant} from '@/lib/data';
const icons=[Footprints,Ship,Bird,Flower2,Plane];
const sheetURL='https://docs.google.com/spreadsheets/d/1ZQs6sk8y13ZUWPlnbC3amFvSwp9ItV7yJtvxLgeMM0E/edit?usp=sharing';
const labelDate=(d:string)=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',timeZone:'UTC'}).format(new Date(d+'T00:00:00Z'));
const fullDate=(d:string)=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(d+'T00:00:00Z'));
function Choice({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:{value:string;label:string}[]}){return <div className="filter-field"><label>{label}</label><Select value={value} onValueChange={set}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;}
function csvCell(v:unknown){let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
function download(name:string,rows:unknown[][]){const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function Dashboard(){
 const [auth,setAuth]=useState<boolean|null>(null),[id,setID]=useState(''),[password,setPassword]=useState(''),[loginError,setLoginError]=useState(''),[busy,setBusy]=useState(false);
 const [data,setData]=useState<LiveData|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[date,setDate]=useState('all'),[activity,setActivity]=useState('all'),[hotel,setHotel]=useState('all'),[search,setSearch]=useState(''),[tab,setTab]=useState('overview'),[rawView,setRawView]=useState(false),[detail,setDetail]=useState<Participant|null>(null),[copied,setCopied]=useState(false);
 useEffect(()=>{fetch('/api/session').then(r=>r.json()).then((v:any)=>setAuth(!!v.authenticated)).catch(()=>setAuth(false));},[]);
 const refresh=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/data',{cache:'no-store'});const v=await r.json() as LiveData & {error?:string;ok?:boolean};if(r.status===401){setAuth(false);return;}if(!r.ok)throw Error(v.error||'The request could not be completed.');setData(v);setError('');}catch(e){setError(e instanceof Error?e.message:'Refresh failed. Please try again.');}finally{setLoading(false);}},[]);
 useEffect(()=>{if(!auth)return;refresh();const interval=setInterval(()=>{if(!document.hidden)refresh();},60000);return()=>clearInterval(interval);},[auth,refresh]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setLoginError('');try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,password})});const v=await r.json() as LiveData & {error?:string;ok?:boolean};if(!r.ok)throw Error(v.error||'The request could not be completed.');setPassword('');setAuth(true);}catch(e){setLoginError(e instanceof Error?e.message:'Could not sign in.');}finally{setBusy(false);}}
 async function logout(){await fetch('/api/logout',{method:'POST'});setAuth(false);setData(null);setDetail(null);}
 const dates=useMemo(()=>[...new Set(data?.selections.map(s=>s.date)||[])].sort(),[data]);
 const hotels=useMemo(()=>[...new Set(data?.responses.map(p=>p.hotel).filter(Boolean)||[])].sort((a,b)=>a.localeCompare(b)),[data]);
 const matchPerson=useCallback((p:Participant)=>(hotel==='all'||p.hotel===hotel)&&(!search||[p.name,p.contact,p.hotel,p.room,p.email].join(' ').toLowerCase().includes(search.toLowerCase())),[hotel,search]);
 const filtered=useMemo(()=>(data?.selections||[]).filter(s=>(date==='all'||s.date===date)&&(activity==='all'||s.activity===activity)&&matchPerson(s.person)),[data,date,activity,matchPerson]);
 const participants=useMemo(()=>{
  const map=new Map<string,Participant>();filtered.forEach(s=>{const old=map.get(s.person.id);if(!old||old.row<s.person.row)map.set(s.person.id,s.person);});
  if(date==='all'&&activity==='all')data?.participants.filter(matchPerson).forEach(p=>{if(!map.has(p.id))map.set(p.id,p);});
  return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name));
 },[filtered,data,date,activity,matchPerson]);
 const responseRows=useMemo(()=>{const ids=new Set(participants.map(p=>p.id));return (data?.responses||[]).filter(p=>ids.has(p.id)&&matchPerson(p)).sort((a,b)=>b.row-a.row);},[data,participants,matchPerson]);
 const demand=useMemo(()=>ACTIVITY_INFO.map(a=>({...a,total:filtered.filter(s=>s.activity===a.name).length,short:a.name==='Helicopter Joy Ride'?'Helicopter':a.name})),[filtered]);
 const matrix=useMemo(()=>dates.map(d=>{const row:Record<string,string|number>={date:labelDate(d),iso:d,total:0};ACTIVITY_INFO.forEach(a=>{const n=filtered.filter(s=>s.date===d&&s.activity===a.name).length;row[a.name]=n;row.total=Number(row.total)+n;});return row;}),[filtered,dates]);
 const max=Math.max(0,...matrix.flatMap(r=>ACTIVITY_INFO.map(a=>Number(r[a.name])))),lead=Math.max(0,...demand.map(a=>a.total));
 const leader=lead?demand.filter(a=>a.total===lead).map(a=>a.name).join(' / '):'—';
 const dayLead=Math.max(0,...matrix.map(m=>Number(m.total))),busiest=dayLead?matrix.filter(m=>m.total===dayLead).map(m=>String(m.date)).join(' / '):'—';
 const rows=rawView?responseRows:participants;
 function reset(){setDate('all');setActivity('all');setHotel('all');setSearch('');}
 function choose(d:string,a:string){setDate(d);setActivity(a);setTab('participants');}
 function exportView(){const extra=[...new Set(rows.flatMap(p=>Object.keys(p.fields)))];download(`MPTM2026_${rawView?'Responses':'Participants'}_${date}_${activity.replaceAll(' ','_')}.csv`,[['Name','Contact','Hotel','Room','Timestamp','Selected dates','Experiences',...extra],...rows.map(p=>{const sel=filtered.filter(s=>s.person.id===p.id);return [p.name,p.contact,p.hotel,p.room,p.timestamp,[...new Set(sel.map(s=>fullDate(s.date)))].join('; '),[...new Set(sel.map(s=>s.activity))].join('; '),...extra.map(h=>p.fields[h]||'')];})]);}
 const briefing=()=>`MPTM 2026 — Morning Experiences\n${date==='all'?'All registered dates':fullDate(date)}${hotel==='all'?'':' | '+hotel}\nParticipants: ${participants.length}\nActivity selections: ${filtered.length}\n\n${demand.filter(a=>a.total>0).map(a=>`${a.name}: ${a.total}\n${a.place} | ${a.time}`).join('\n\n')}\n\nReporting details: hotel Help Desk.\nWear comfortable walking shoes and light, neutral-coloured clothing.\nContact: Mr. Brajmohan Vishwakarma, MPTB\n+91 8817369119\nUpdated: ${new Date(data?.sourceUpdatedAt||Date.now()).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST`;
 async function copyBrief(){try{await navigator.clipboard.writeText(briefing());setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{setError('Clipboard access is unavailable. Use Download summary instead.');}}
 if(auth===null)return <div className="boot"><img src="/mptm-logo.png" alt="Madhya Pradesh Travel Mart 2026"/><p>Opening morning experiences…</p></div>;
 if(!auth)return <main className="login"><section className="login-art"><img src="/morning-experiences.jpg" alt="MPTM 2026 Bhopal morning activities event artwork"/><div className="login-art-caption"><span>MADHYA PRADESH TRAVEL MART</span><h1>A morning in the<br/>heart of India.</h1><p>Bhopal · 7–10 October 2026</p></div></section><section className="login-panel"><div className="login-brands"><img src="/mptm-logo.png" alt="MPTM 2026"/><img src="/mp-tourism-logo.png" alt="Madhya Pradesh Tourism"/></div><div className="login-form"><span className="eyebrow">COORDINATOR ACCESS</span><h2>Morning experiences</h2><p>Sign in to view live registrations,<br/>plan activities and extract participant lists.</p><form onSubmit={login}><label htmlFor="login-id">Login ID</label><Input id="login-id" value={id} onChange={e=>setID(e.target.value)} autoComplete="username" placeholder="Enter your login ID" required/><label htmlFor="login-pass">Password</label><Input id="login-pass" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" placeholder="Enter your password" required/>{loginError&&<p className="form-error" role="alert">{loginError}</p>}<Button type="submit" disabled={busy}>{busy?'Signing in…':'Sign in'}<LockKeyhole size={17}/></Button></form><div className="login-foot"><Eye size={17}/>Read-only access · Sheet data stays unchanged</div></div><footer>Madhya Pradesh Tourism Board · MPTM 2026</footer></section></main>;
 return <div className="app-shell"><header className="topbar"><div className="brand"><img src="/mptm-logo.png" alt="MPTM 2026"/><div className="brand-divider"/><div><span>MADHYA PRADESH TRAVEL MART</span><strong>Morning Experiences</strong></div></div><div className="header-actions"><img src="/mp-tourism-logo.png" alt="Madhya Pradesh Tourism"/><span className="access-pill"><Eye size={14}/>View only</span><Button variant="ghost" onClick={logout} aria-label="Sign out"><LogOut size={18}/><span>Sign out</span></Button></div></header>
 <main className="workspace"><div className="page-heading"><div><span className="eyebrow">BHOPAL · MPTM 2026</span><h1>Morning activity dashboard</h1></div><div className="sync"><div className="sync-label"><span className={'sync-dot '+(error?'failed':'')}/>{error?'Refresh needed':data?'Live Google Sheet':'Connecting…'}<small>{data?`Updated ${new Date(data.sourceUpdatedAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'})} IST · refreshes every minute`:'Loading current responses'}</small></div><Button variant="outline" onClick={refresh} disabled={loading} aria-label="Refresh data"><RefreshCw size={17} className={loading?'spin':''}/></Button></div></div>
 {error&&<div className="error-banner" role="alert">{error}{data&&' Displaying the last successful refresh.'}</div>}
 {data?.invalidDates? <div className="error-banner">{data.invalidDates} date choices could not be read and are excluded from activity counts. Review those values in the source sheet.</div>:null}
 <div className="filterbar"><Choice label="Activity date" value={date} set={setDate} options={[{value:'all',label:'All dates'},...dates.map(d=>({value:d,label:fullDate(d)}))]}/><Choice label="Experience" value={activity} set={setActivity} options={[{value:'all',label:'All experiences'},...ACTIVITY_INFO.map(a=>({value:a.name,label:a.name}))]}/><Choice label="Hotel" value={hotel} set={setHotel} options={[{value:'all',label:'All hotels'},...hotels.map(h=>({value:h,label:h}))]}/><div className="search-field"><label>Find a delegate</label><div><Search size={17}/><Input aria-label="Find a delegate" placeholder="Name, contact or room" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><Button variant="ghost" className="reset" onClick={reset}>Reset</Button></div>
 <div className="kpi-grid"><article><span>Activity selections<Layers size={19}/></span><strong>{data?filtered.length:'—'}</strong><small>One participant × date × experience</small></article><article><span>Participants<Users size={19}/></span><strong>{data?participants.length:'—'}</strong><small>Unique delegates in this view</small></article><article><span>Leading experience<Footprints size={19}/></span><strong className="text-kpi">{data?leader:'—'}</strong><small>{lead?`${lead} activity selections`:'No matching selections'}</small></article><article><span>Busiest date<CalendarDays size={19}/></span><strong className="text-kpi">{data?busiest:'—'}</strong><small>{dayLead?`${dayLead} activity selections`:'No matching selections'}</small></article></div>
 <Tabs value={tab} onValueChange={setTab}><div className="view-navigation"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="participants">Participant lists</TabsTrigger><TabsTrigger value="guide">Event guide</TabsTrigger></TabsList><div className="view-actions"><Button variant="outline" onClick={copyBrief} disabled={!data}>{copied?<Check size={16}/>:<Copy size={16}/>}<span>{copied?'Copied':'Copy briefing'}</span></Button><Button onClick={exportView} disabled={!data}><Download size={16}/>Export view</Button></div></div>
 <TabsContent value="overview"><div className="activity-strip">{demand.map((a,i)=>{const Icon=icons[i];return <button className={'activity-tile '+(activity===a.name?'selected':'')} key={a.name} onClick={()=>setActivity(activity===a.name?'all':a.name)} style={{'--activity-color':a.color} as React.CSSProperties}><Icon size={23}/><span>{a.name}<small>{a.place}</small></span><strong>{data?a.total:'—'}</strong></button>;})}</div>
 <div className="charts-grid"><section className="surface demand-chart"><div className="section-heading"><h2>Activity demand</h2><span>Selections in this view</span></div><div className="chart-frame">{!data?<p className="empty">Loading registrations…</p>:!filtered.length?<p className="empty">No activity selections match your filters.</p>:<ResponsiveContainer width="100%" height="100%"><BarChart data={demand} layout="vertical" margin={{left:8,right:25}}><CartesianGrid horizontal={false} stroke="#e7edf1"/><XAxis type="number" allowDecimals={false} tick={{fontSize:13}}/><YAxis dataKey="short" type="category" width={115} tick={{fontSize:13}} axisLine={false} tickLine={false}/><Tooltip cursor={{fill:'#f2f5f8'}}/><Bar dataKey="total" name="Selections" radius={[0,5,5,0]} barSize={22} onClick={(v:any)=>{const name=v?.payload?.name||v?.name;if(ACTIVITY_INFO.some(a=>a.name===name))setActivity(name);}}>{demand.map(a=><Cell key={a.name} fill={a.color}/>)}</Bar></BarChart></ResponsiveContainer>}</div></section>
 <section className="surface share-chart"><div className="section-heading"><h2>Experience share</h2><span>Activity selections</span></div><div className="chart-frame">{!filtered.length?<p className="empty">No activity selections to display.</p>:<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={demand.filter(a=>a.total>0)} dataKey="total" nameKey="name" innerRadius={65} outerRadius={90} paddingAngle={3} onClick={(v:any)=>setActivity(v.name)}>{demand.filter(a=>a.total>0).map(a=><Cell key={a.name} fill={a.color}/>)}</Pie><Tooltip/><Legend iconType="circle" iconSize={8} wrapperStyle={{fontSize:13}}/></PieChart></ResponsiveContainer>}</div></section>
 <section className="surface dates-chart"><div className="section-heading"><h2>Date-wise demand</h2><span>Plan each morning</span></div><div className="chart-frame">{!filtered.length?<p className="empty">No activity selections to display.</p>:<ResponsiveContainer width="100%" height="100%"><BarChart data={matrix} margin={{left:0,right:10}}><CartesianGrid vertical={false} stroke="#e7edf1"/><XAxis dataKey="date" tick={{fontSize:13}}/><YAxis allowDecimals={false} tick={{fontSize:13}} width={28}/><Tooltip/><Legend iconType="circle" iconSize={8} wrapperStyle={{fontSize:12}}/>{ACTIVITY_INFO.map(a=><Bar key={a.name} dataKey={a.name} stackId="day" fill={a.color} maxBarSize={55}/>)}</BarChart></ResponsiveContainer>}</div></section></div>
 <section className="surface heatmap"><div className="section-heading"><div><h2>Daily activity matrix</h2><p>Select a cell to open its participant list.</p></div><span className="heat-legend">Lower demand<i/>Higher demand</span></div><Table><TableHeader><TableRow><TableHead>Date</TableHead>{ACTIVITY_INFO.map(a=><TableHead key={a.name}>{a.name}</TableHead>)}<TableHead>Total</TableHead></TableRow></TableHeader><TableBody>{matrix.map(r=><TableRow key={String(r.iso)}><TableCell className="date-cell">{labelDate(String(r.iso))}<small>{String(r.iso).slice(0,4)}</small></TableCell>{ACTIVITY_INFO.map(a=>{const n=Number(r[a.name]);return <TableCell key={a.name}><button aria-label={`${a.name} on ${fullDate(String(r.iso))}: ${n} selections`} className="heat-cell" onClick={()=>choose(String(r.iso),a.name)} style={{background:n?`rgba(8,107,109,${.09+(max?n/max:0)*.78})`:'#f4f6f8',color:max&&n/max>.55?'white':'#173b50'}}>{n}</button></TableCell>;})}<TableCell className="total-cell">{r.total}</TableCell></TableRow>)}</TableBody></Table>{!matrix.length&&<p className="empty">Dates will appear when registration data is loaded.</p>}<div className="matrix-foot">Counts follow the active filters. Repeated activity columns and identical repeat selections are combined.</div></section></TabsContent>
 <TabsContent value="participants"><section className="surface participant-surface"><div className="section-heading"><div><h2>{rawView?'Form response records':'Coordinator participant list'}</h2><p>{date==='all'?'All registered dates':fullDate(date)} · {activity==='all'?'All experiences':activity} · {rows.length} {rawView?'responses':'participants'}</p></div><div className="list-actions"><label className="check-label"><Checkbox checked={rawView} onCheckedChange={v=>setRawView(v===true)}/>Show repeat submissions</label><Button variant="outline" onClick={()=>window.print()}><Printer size={16}/>Print</Button></div></div><Table><TableHeader><TableRow><TableHead>Delegate</TableHead><TableHead>Contact</TableHead><TableHead>Hotel / room</TableHead><TableHead>Dates / experiences</TableHead><TableHead>Submitted</TableHead><TableHead/></TableRow></TableHeader><TableBody>{rows.map((p,ix)=>{const sel=filtered.filter(s=>s.person.id===p.id);return <TableRow key={p.id+':'+p.row+':'+ix}><TableCell><strong>{p.name}</strong>{p.email&&<small>{p.email}</small>}</TableCell><TableCell>{p.contact||<span className="muted">Not provided</span>}</TableCell><TableCell>{p.hotel||'Not provided'}<small>Room: {p.room||'Not provided'}</small></TableCell><TableCell><div className="tag-list">{[...new Set(sel.map(s=>s.activity))].map(a=><span key={a}>{a}</span>)}</div><small>{[...new Set(sel.map(s=>labelDate(s.date)))].join(', ')||'No dated activity choice'}</small></TableCell><TableCell className="timestamp-cell">{p.timestamp}</TableCell><TableCell><Button variant="ghost" onClick={()=>setDetail(p)} aria-label={`View all response fields for ${p.name}`}><ChevronRight size={18}/></Button></TableCell></TableRow>;})}</TableBody></Table>{!rows.length&&<p className="empty">{data?'No participants match these filters. Try another date or experience.':'Loading current registrations…'}</p>}<div className="matrix-foot">{rawView?'All submission records for matching participants are shown.':'One row per delegate. The latest matching response provides contact and hotel details.'} Total source submissions: {data?.submissions??'—'}.</div></section></TabsContent>
 <TabsContent value="guide"><div className="guide-heading"><div><span className="eyebrow">MORNING EXPERIENCE REGISTRATION</span><h2>Explore Bhopal during your stay.</h2><p>Cultural, natural and recreational experiences for MPTM delegates.</p></div><Button variant="outline" onClick={()=>download('MPTM2026_Event_Guide.csv',[['Experience','Dates','Time','Meeting point','Reporting note'],...ACTIVITY_INFO.map(a=>[a.name,a.dates,a.time,a.place,a.note])])}><Download size={16}/>Extract event details</Button></div><div className="experience-grid">{ACTIVITY_INFO.map((a,i)=>{const Icon=icons[i];return <article className="surface experience" key={a.name} style={{'--activity-color':a.color} as React.CSSProperties}><div className="experience-icon"><Icon size={25}/></div><h3>{a.name==='Bird Walk'?'Bird Watching / Bird Walk':a.name}</h3><p><MapPin size={17}/>{a.place}</p><p><CalendarDays size={17}/>{a.dates}</p><p><Clock size={17}/>{a.time}</p><div>{a.note}</div><Button variant="outline" onClick={()=>{setActivity(a.name);setTab('participants');}}>View participants</Button></article>;})}</div><div className="guide-notes surface"><div><h3>Before you join</h3><ul><li>Delegates may select one or more experiences based on availability.</li><li>Confirm reporting time and meeting point with the Help Desk at your hotel.</li><li>Wear comfortable walking shoes and light, breathable clothing in neutral colours.</li></ul></div><div className="contact-card"><span>MPTB COORDINATION</span><strong>Mr. Brajmohan Vishwakarma</strong><a href="tel:+918817369119"><Phone size={17}/>+91 8817369119</a></div></div></TabsContent></Tabs>
 <footer className="app-footer"><span>MPTM 2026 · Madhya Pradesh Tourism Board</span><span>{data?.submissions??'—'} form submissions · <a href={sheetURL} target="_blank" rel="noreferrer">View source Sheet<ExternalLink size={13}/></a></span></footer></main>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="response-dialog"><DialogHeader><DialogTitle>{detail?.name}</DialogTitle><DialogDescription>Full response record · source row {detail?.row}</DialogDescription></DialogHeader><div className="response-fields">{detail&&Object.entries(detail.fields).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'—'}</dd></div>)}</div><Button onClick={()=>{if(detail)download('MPTM2026_Response.csv',[['Field','Response'],...Object.entries(detail.fields)]);}}><Download size={16}/>Export this response</Button></DialogContent></Dialog></div>;
}
